/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import Grafo.Grafo;

/**
 *
 * @author Maryr
 */
public class FrmBFS extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBFS.class.getName());

    /**
     * Creates new form FrmBFS
     */
    public FrmBFS(Grafo grafo, String ciudadInicial) {
        initComponents();
        setLocationRelativeTo(null);
        cargarVisualizadorBFS(grafo, ciudadInicial);
    }

    private void cargarVisualizadorBFS(Grafo grafo, String ciudadInicial) {
        pnlBFS.removeAll();
        VisualizadorBFS panel = new VisualizadorBFS(grafo, ciudadInicial);
        panel.setSize(pnlBFS.getWidth(), pnlBFS.getHeight());
        panel.setLocation(0, 0);
        pnlBFS.setLayout(new java.awt.BorderLayout());
        pnlBFS.add(panel, java.awt.BorderLayout.CENTER);
        pnlBFS.revalidate();
        pnlBFS.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBFS = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBFS.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout pnlBFSLayout = new javax.swing.GroupLayout(pnlBFS);
        pnlBFS.setLayout(pnlBFSLayout);
        pnlBFSLayout.setHorizontalGroup(
            pnlBFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBFSLayout.setVerticalGroup(
            pnlBFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        btnRegresar.setBackground(new java.awt.Color(18, 44, 74));
        btnRegresar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 204, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(pnlBFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        Controlador.Controlador.mostrarMenu();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel pnlBFS;
    // End of variables declaration//GEN-END:variables
}
