/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import Grafo.Grafo;
import javax.swing.JFrame;

/**
 *
 * @author Jack Murrieta
 */
public class FrmDFS extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDFS.class.getName());

    /**
     * Creates new form FrmDFS
     */
    public FrmDFS(Grafo grafo, String ciudadInicial) {
        initComponents();
        setLocationRelativeTo(null);

        pnlDFS.setLayout(new java.awt.BorderLayout());

        cargarVisualizadorDFS(grafo, ciudadInicial);

        // Pantalla completa
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void cargarVisualizadorDFS(Grafo grafo, String ciudadInicial) {
        pnlDFS.removeAll();

        VisualizadorDFS panel = new VisualizadorDFS(grafo, ciudadInicial);

        pnlDFS.add(panel, java.awt.BorderLayout.CENTER);
        pnlDFS.revalidate();
        pnlDFS.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        pnlDFS = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setBackground(new java.awt.Color(18, 44, 74));
        btnRegresar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 204, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlDFSLayout = new javax.swing.GroupLayout(pnlDFS);
        pnlDFS.setLayout(pnlDFSLayout);
        pnlDFSLayout.setHorizontalGroup(
            pnlDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlDFSLayout.setVerticalGroup(
            pnlDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDFS, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked

//        FrmMenu frmMenu = new FrmMenu();
//        frmMenu.setVisible(true);
//        this.dispose();
        Controlador.Controlador.mostrarMenu();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Controlador.Controlador.mostrarMenu();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel pnlDFS;
    // End of variables declaration//GEN-END:variables
}
