/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import GrafoOaxaca.GrafoOaxaca;

/**
 *
 * @author Jack Murrieta
 */
public class FrmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBox = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnTabla = new javax.swing.JButton();
        btnMostrarGrafo = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        btnAEM = new javax.swing.JButton();
        btnRC = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBox.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(18, 44, 74));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Oaxaca Grafo");

        btnTabla.setBackground(new java.awt.Color(1, 34, 74));
        btnTabla.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnTabla.setForeground(new java.awt.Color(204, 204, 255));
        btnTabla.setText("Mostrar tabla");
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });

        btnMostrarGrafo.setBackground(new java.awt.Color(18, 44, 74));
        btnMostrarGrafo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnMostrarGrafo.setForeground(new java.awt.Color(204, 204, 255));
        btnMostrarGrafo.setText("Mostrar Grafo");
        btnMostrarGrafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarGrafoMouseClicked(evt);
            }
        });
        btnMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGrafoActionPerformed(evt);
            }
        });

        btnBFS.setBackground(new java.awt.Color(18, 44, 74));
        btnBFS.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnBFS.setForeground(new java.awt.Color(204, 204, 255));
        btnBFS.setText("BFS");
        btnBFS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBFSMouseClicked(evt);
            }
        });

        btnDFS.setBackground(new java.awt.Color(18, 44, 74));
        btnDFS.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnDFS.setForeground(new java.awt.Color(204, 204, 255));
        btnDFS.setText("DFS");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });

        btnAEM.setBackground(new java.awt.Color(18, 44, 74));
        btnAEM.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnAEM.setForeground(new java.awt.Color(204, 204, 255));
        btnAEM.setText("Arbol Expansion Minima");
        btnAEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAEMMouseClicked(evt);
            }
        });
        btnAEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAEMActionPerformed(evt);
            }
        });

        btnRC.setBackground(new java.awt.Color(18, 44, 74));
        btnRC.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnRC.setForeground(new java.awt.Color(204, 204, 255));
        btnRC.setText("Ruta Corta");
        btnRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMouseClicked(evt);
            }
        });

        btnReporte.setBackground(new java.awt.Color(18, 44, 74));
        btnReporte.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(204, 204, 255));
        btnReporte.setText("Reportes Complejidad");

        btnSalir.setBackground(new java.awt.Color(18, 44, 74));
        btnSalir.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBoxLayout = new javax.swing.GroupLayout(pnlBox);
        pnlBox.setLayout(pnlBoxLayout);
        pnlBoxLayout.setHorizontalGroup(
            pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoxLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBoxLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAEM, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnBFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRC, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .addComponent(btnMostrarGrafo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(pnlBoxLayout.createSequentialGroup()
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBoxLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBoxLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnReporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoxLayout.setVerticalGroup(
            pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoxLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDFS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAEM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(pnlBox, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAEMActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        // TODO add your handling code here:
        Controlador.Controlador.mostrarFrmTabla();
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarGrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarGrafoMouseClicked
        Controlador.Controlador.mostrarFrmMostrarGrafo();
    }//GEN-LAST:event_btnMostrarGrafoMouseClicked

    private void btnMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGrafoActionPerformed

    }//GEN-LAST:event_btnMostrarGrafoActionPerformed

    private void btnBFSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBFSMouseClicked
        Controlador.Controlador.mostrarFrmSeleccionCiudadSemilla("BFS");
    }//GEN-LAST:event_btnBFSMouseClicked

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
       Controlador.Controlador.mostrarFrmSeleccionCiudadSemilla("DFS");
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnAEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAEMMouseClicked
        Controlador.Controlador.mostrarFrmMST();
    }//GEN-LAST:event_btnAEMMouseClicked

    private void btnRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMouseClicked
        Controlador.Controlador.mostrarFrmSeleccionDijkstra();
    }//GEN-LAST:event_btnRCMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAEM;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnMostrarGrafo;
    private javax.swing.JButton btnRC;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBox;
    // End of variables declaration//GEN-END:variables
}
