/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

/**
 *
 * @author Jack Murrieta
 */
public class FrmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlBox = new javax.swing.JPanel();
        btnTabla = new javax.swing.JButton();
        btnGrafo = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        btnAEM = new javax.swing.JButton();
        btnRC = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Oaxaca Grafo");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        pnlBox.setLayout(new java.awt.GridLayout(0, 1, 0, 15));

        btnTabla.setText("Mostrar tabla");
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });
        pnlBox.add(btnTabla);

        btnGrafo.setText("Mostrar Grafo");
        pnlBox.add(btnGrafo);

        btnBFS.setText("BFS");
        pnlBox.add(btnBFS);

        btnDFS.setText("DFS");
        pnlBox.add(btnDFS);

        btnAEM.setText("Arbol Expansion Minima");
        btnAEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAEMActionPerformed(evt);
            }
        });
        pnlBox.add(btnAEM);

        btnRC.setText("Ruta Corta");
        pnlBox.add(btnRC);

        btnReporte.setText("Reportes Complejidad");
        pnlBox.add(btnReporte);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBox.add(btnSalir);

        getContentPane().add(pnlBox, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAEMActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        // TODO add your handling code here:
        Controlador.Controlador.mostrarFrmTabla();
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAEM;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnGrafo;
    private javax.swing.JButton btnRC;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBox;
    // End of variables declaration//GEN-END:variables
}
