/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import Grafo.Grafo;

/**
 *
 * @author AlexNieblas10
 */
public class FrmSeleccionDijkstra extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSeleccionDijkstra.class.getName());
    private Grafo grafo;

    /**
     * Creates new form FrmSeleccionDijkstra
     */
    public FrmSeleccionDijkstra(Grafo grafo) {
        this.grafo = grafo;
        initComponents();
        setLocationRelativeTo(null);
        cargarVertices();
    }

    private void cargarVertices() {
        cbBoxOrigen.removeAllItems();
        cbBoxDestino.removeAllItems();
        for (String nombreVertice : grafo.getVertices().keySet()) {
            cbBoxOrigen.addItem(nombreVertice);
            cbBoxDestino.addItem(nombreVertice);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbBoxOrigen = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        cbBoxDestino = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cbBoxOrigen.setBackground(new java.awt.Color(204, 204, 255));
        cbBoxOrigen.setForeground(new java.awt.Color(18, 44, 74));
        cbBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>());

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(18, 44, 74));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ruta Más Corta - Dijkstra");

        btnAceptar.setBackground(new java.awt.Color(18, 44, 74));
        btnAceptar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(204, 204, 255));
        btnAceptar.setText("Calcular Ruta");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblOrigen.setBackground(new java.awt.Color(204, 204, 255));
        lblOrigen.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(18, 44, 74));
        lblOrigen.setText("Ciudad Origen:");

        lblDestino.setBackground(new java.awt.Color(204, 204, 255));
        lblDestino.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(18, 44, 74));
        lblDestino.setText("Ciudad Destino:");

        cbBoxDestino.setBackground(new java.awt.Color(204, 204, 255));
        cbBoxDestino.setForeground(new java.awt.Color(18, 44, 74));
        cbBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>());

        btnRegresar.setBackground(new java.awt.Color(18, 44, 74));
        btnRegresar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 204, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnRegresar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbBoxDestino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDestino, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbBoxOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOrigen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String ciudadOrigen = cbBoxOrigen.getSelectedItem().toString();
        String ciudadDestino = cbBoxDestino.getSelectedItem().toString();

        if (ciudadOrigen.equals(ciudadDestino)) {
            Controlador.Controlador.mostrarError("El origen y destino deben ser diferentes");
            return;
        }

        Controlador.Controlador.mostrarFrmDijkstra(ciudadOrigen, ciudadDestino);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Controlador.Controlador.mostrarMenu();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbBoxDestino;
    private javax.swing.JComboBox<String> cbBoxOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
