/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs;

import Grafo.Grafo;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author Jack Murrieta
 */
public class PnlScrollGrafo extends javax.swing.JPanel {
    
    private JScrollPane scrollPane;
    private PnlGrafo pnlGrafo;

    /**
     * Creates new form PnlScrollGrafo
     */
    public PnlScrollGrafo(Grafo grafo) {
        initComponents();
        setLayout(new BorderLayout());
        agregarScrollGrafo(grafo);
        
    }
    
    public void agregarScrollGrafo(Grafo grafo) {
        if (grafo == null) {
            return;
        }
        
        if (scrollPane != null) {
            remove(scrollPane);
        }
        
        pnlGrafo = new PnlGrafo(grafo);
        pnlGrafo.setPreferredSize(new java.awt.Dimension(2000, 1200));
        
        scrollPane = new JScrollPane(pnlGrafo);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
        add(scrollPane, BorderLayout.CENTER);
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
