/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs;

import Grafo.Arista;
import Grafo.Grafo;
import Grafo.Vertice;
import GrafoOaxaca.GrafoOaxaca;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jack Murrieta
 */
public class PnlTablaGrafo extends javax.swing.JPanel {

    //grafoOaxaca desde main
    private Grafo grafo;

    /**
     * Creates new form PnlTablaGrafo
     */
    public PnlTablaGrafo(Grafo grafo) {
        this.grafo = grafo;
        initComponents();
        llenarTabla();

    }

    //añadir info a la tabla
    private void llenarTabla() {
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);

        // Recorrer vertices
        for (Map.Entry<String, Vertice> entry : grafo.getVertices().entrySet()) {
            String nombreVertice = entry.getKey();
            Vertice vertice = entry.getValue();

            // Recorrer 
            for (Arista arista : vertice.getAristas()) {
                // Crear una fila de objetos con los datos
                Object[] fila = {
                    //origen
                    nombreVertice,
                    //destino
                    arista.getDestino().getNombre(),
                    //peso
                    arista.getPeso()
                };
                modelo.addRow(fila);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tabla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origen", "Destino", "Peso(Km)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
