/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs;

import Grafo.Vertice;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Jack Murrieta
 */
public class PnlVertice extends javax.swing.JPanel {

    private Vertice vertice;
    private boolean actual = false; //validar en los recorrios cuando sea el actual es rojo
    private Color colorActual = Color.RED;
    private Color colorDefault = new Color(18, 44, 74);
    private int posX;
    private int posY;

    /**
     * Creates new form PnlVertice
     */
    public PnlVertice(Vertice vertice, boolean actual) {
        this.actual = actual;
        this.vertice = vertice;
        initComponents();
        setOpaque(false); // Fondo transparente
        setPreferredSize(new Dimension(80, 80)); // Tamaño del vértice
        lblNombre.setFont(new Font("Arial", Font.BOLD, 11));
        lblNombre.setForeground(Color.WHITE);
        configurarLabel(vertice.getNombre());
        setActual(actual);

    }

    public void setPosicion(int x, int y) {
        this.posX = x;
        this.posY = y;
        setBounds(x, y, getWidth(), getHeight());
    }

    public int getPosX() {
        return posX + getWidth() / 2; // centro horizontal del vértice
    }

    public int getPosY() {
        return posY + getHeight() / 2; // centro vertical del vértice
    }

    public Vertice getVertice() {
        return vertice;
    }

    public void configurarLabel(String nombre) {
        // Convierte los espacios en saltos de línea para nombres largos
        String textoFormateado = "<html><div style='text-align:center; width:70px;'>"
                + nombre.replace(" ", "<br>") + "</div></html>";
        lblNombre.setText(textoFormateado);
    }

    /**
     * Cambia el estado del vértice (para mostrar en rojo si es el actual)
     */
    public void setActual(boolean actual) {
        this.actual = actual;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        Color color = actual ? colorActual : colorDefault;

        int diametro = 60;
        int x = (getWidth() - diametro) / 2;
        int y = (getHeight() - diametro) / 2;
        g2d.setColor(color);
        g2d.fillOval(x, y, diametro, diametro);

        // borde negro
        g2d.setColor(Color.BLACK);
        g2d.drawOval(x, y, diametro, diametro);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("NOMBRE DE LA CIUDAD EN EL VERTICE EJEMPLO");
        add(lblNombre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
